=== PatriciaRisGar/libreConfiguracion/Actividad 1 - Diseño XML y validacion/Tarea 1/empresa.dtd
<!ELEMENT empresa ((departamentoInformatica)?, (departamentoPeople)?)>
<!ELEMENT departamentoInformatica (empleado+)>
<!ELEMENT departamentoPeople (empleado+)>
<!ELEMENT empleado (nombre,apellidos,cargo,telefonoMovil,telefonoFijo?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT telefonoMovil (#PCDATA)>
<!ELEMENT telefonoFijo (#PCDATA)>

=== PatriciaRisGar/libreConfiguracion/Actividad 1 - Diseño XML y validacion/Tarea 1/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<!DOCTYPE empresa SYSTEM "./empresa.dtd">


<empresa>
  <departamentoInformatica>
    <empleado>
      <nombre>Ricardo</nombre>
      <apellidos>Rodriguez Garcia</apellidos>
      <cargo>Secretario</cargo>
      <telefonoMovil>722894367</telefonoMovil>
      <telefonoFijo>955789823</telefonoFijo>
    </empleado>
    <empleado>
      <nombre>Javi</nombre>
      <apellidos>Garcia Rodriguez</apellidos>
      <cargo>Secretario</cargo>
      <telefonoMovil>636887367</telefonoMovil>
      <telefonoFijo>954657243</telefonoFijo>
    </empleado>
  </departamentoInformatica>
  
  <departamentoPeople>
    <empleado>
      <nombre>Manuel</nombre>
      <apellidos>Diaz Garcia</apellidos>
      <cargo>RRHH Senior</cargo>
      <telefonoMovil>722894367</telefonoMovil>
      <telefonoFijo>955789823</telefonoFijo>
    </empleado>
    <empleado>
      <nombre>Sandra</nombre>
      <apellidos>Garcia Gonz√°lez</apellidos>
      <cargo>RRHH Junior</cargo>
      <telefonoMovil>636887367</telefonoMovil>
      <telefonoFijo>954657243</telefonoFijo>
    </empleado>
  </departamentoPeople>
</empresa>
