=== PatriciaRisGar/libreConfiguracion/Actividad 1 - Diseño XML y validacion/Tarea 2/clubPadel.dtd
<!ELEMENT clubPadel (persona)+>
<!ELEMENT persona (nombre,apellido1,(apellido2?),(telefono?)+, (correo+), socio)>
<!ATTLIST persona 
  genero (Masculino|Femenino) #REQUIRED 
  id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT socio (#PCDATA)>

=== PatriciaRisGar/libreConfiguracion/Actividad 1 - Diseño XML y validacion/Tarea 2/index.xml
<?xml version="1.0" encoding="UTF-8" standalone='no'?>
<!DOCTYPE clubPadel SYSTEM './clubPadel.dtd' >

<clubPadel>
  <persona genero='Femenino' id='1'>
    <nombre>Alberto</nombre>
    <apellido1>Ruiz</apellido1>
    <telefono>650596413 609453423</telefono>
    <correo>aruiz@gmail.com aruiz@hotmail.com</correo>
    <socio>Si</socio>
  </persona>
  <persona genero='Masculino' id='2'>
    <nombre>Antonio</nombre>
    <apellido1>Parez</apellido1>
    <apellido2>Chicón</apellido2>
    <correo>aperez@gmail.com</correo>
    <socio>No</socio>
  </persona>
  <persona genero='Masculino' id='2'>
    <nombre>Amapola</nombre>
    <apellido2>Chicón</apellido2>
    <correo>achicon@gmail.com</correo>
    <socio>No</socio>
  </persona>
</clubPadel>
